// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsyddfdfzfkhkkxmrmxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeWRkZmRmemZraGtreG1ybXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTY1OTYsImV4cCI6MjA3MTg5MjU5Nn0.dK5-PyXsLvD60elEGQWHc3t-lDg9klBqNbjuektKIhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});